### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by Dason-zdc** [zepen/predict_Lottery_ticket#16]
问题1： bs4 只能安装 0.0.1版本 
```
Could not fetch URL https://pypi.org/simple/bs4/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/bs4/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:841)'),)) - skipping
ERROR: Could not find a version that satisfies the requirement bs4==4.9.3
ERROR: No matching distribution found for bs4==4.9.3
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:841)'),)) - skipping
```
问题2： 执行 python get_train_data.py
```
Traceback (most recent call last):
  File "get_train_data.py", line 64, in <module>
    print("[INFO] 最新一期期号：{}".format(get_current_number()))
  File "get_train_data.py", line 18, in get_current_number
    soup = BeautifulSoup(r.text, "lxml")
  File "E:\software\Python\lib\site-packages\bs4\__init__.py", line 246, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```
问题3： 执行python run_api.py
```
Traceback (most recent call last):
  File "run_api.py", line 15, in <module>
    model_red_1 = load_model('model/lstm_model_红球号码_1.h5')
  File "E:\software\Python\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "E:\software\Python\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: model/lstm_model_红球号码_1.h5/{saved_model.pbtxt|saved_model.pb}
```

**Comment by zepen** [comment]
Q1:  我是按照我python下，相关库写版本，因为我能成功，没注意相关版本存在差异
Q2：同问题一，我添加一下这个库吧
Q3：是因为没有训练模型，所以模型不存在的吧？
