### ISSUE TITLE
数据不显示

### ISSUE THREAD

**Issue by CPCPOY** [zepen/predict_Lottery_ticket#25]
我使用的虚拟机，所有插件版本都是request.txt里的，除了numpy 是1.19.5以外（如果使用request里的1.17.2，在训练的时候会出现：Python Fatal Error: GC Object already Tracked 的报错。）. Python 是3.6.13.

取数据和训练都顺利完成（会提示没有nvidia驱动，不过也能完成训练）。

运行了run_api.py后，打开 127.0.0.1:5000 是 “Welcome to use!”，如果打开127.0.0.1:5000/predict_api/ ，则报错："GET /predict_api/ HTTP/1.1" 404 -;  如果打开127.0.0.1:5000/predict_api （没有"/")， 则报错：
ERROR in app: Exception on /predict_api [GET]
Traceback (most recent call last):
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_api.py", line 53, in get_predict_result
    diff_number = windows_size - 1
SystemError: unknown opcode
 "GET /predict_api HTTP/1.1" 500 -

是我哪里没配置对吗？请抽空解答下，谢谢。

**Comment by CPCPOY** [comment]
另外发现一个问题，能正常训练的时候，虚拟机的日期是不对的。然后我纠正了错误的时区，并同步到正确时间后，训练就不能正常执行：
  tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory

  tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory

  tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

Segmentation fault

**Comment by zepen** [comment]
我严格限制了tensorflow-cpu版本，默认按照会有gpu的，出现找cuda的问题。建议使用conda创建环境，再pip install -r requirements 进行相关依赖库的安装
